/*                   LEETCODE 389
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t. */

 
class Solution 
{ public: char findTheDifference(string s, string t)
          { char r=0;
            for(char c:s) r=r^c;
            for(char c:t) r=r^c;
           
           return r;
        
          }
};
